@startuml
title IACCDB Computational Dependencies
skinparam noteBackgroundColor #CEFEFE

object score {
  raw grades from judges
}
object pf_result {
  pilot results for flight
  grades * k-values aggregated
  penalties
}
object pfj_result {
  pilot results from judge for flight
  individual judge grades * k-values
  judge rankings of figures
  judge overall score and ranking of flight
}
object jf_result {
  judge metrics for flight
}
object jy_result {
  judge metric rollups for year in category
}
object jc_result {
  judge metric rollups for contest
}
object pc_result {
  pilot results for contest
}
object result {
  soucy
  collegiate
}

score <--o pfj_result
pfj_result <--o pf_result
pf_result <--o pc_result
jf_result <--o jc_result
pf_result <|-- jf_result
jc_result <--o jy_result
pc_result <--o result
pc_result <--o regional_pilots

note "CollegiateComputer" as Coll
pc_result ..> Coll
Coll ..> result

note "find_stars" as Stars
pf_result ..> Stars
Stars ..> pc_result

note "JudgeRollups.compute_jy_results(year)" as JRoll
jc_result ..> JRoll
JRoll ..> jy_result

note "RegionalSeries" as Regional
pc_result ..> Regional
Regional ..> regional_pilots

note "SoucyComputer" as Soucy
pc_result ..> Soucy
Soucy ..> result

note "CategoryRollups.compute_pilot_category_results" as PCR
pf_result ..> PCR
PCR ..> pc_result

note "CategoryRollups.compute_judge_category_results" as PJR
jf_result ..> PJR
PJR ..> jc_result

note "FlightComputer.compute_pf_results" as FCCPF
score ..> FCCPF
FCCPF ..> pf_result
FCCPF ..> pfj_result

note "FlightComputer.compute_jf_results" as FCCJF
pf_result ..> FCCJF
pfj_result ..> FCCJF
FCCJF ..> jf_result

@enduml

